[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.4"
prost-types = "0.13"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
tonic = "0.12.3"
libsql = "0.6.0"


[build-dependencies]
tonic-build = "0.12.3"
